name: GL-MT3600BE Ultimate Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com
  REPO_BRANCH: openwrt-25.12
  CONFIG_FILE: seed.config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/swift
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison gawk gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget subversion patch swig time
        sudo timedatectl set-timezone "${{ env.TZ }}"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update & Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Inject Configuration & System Optimization
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        cd openwrt
        sed -i 's/192.168.1.1/192.168.6.1/g' package/base-files/files/bin/config_generate
        sed -i '/disabled=1/s/disabled=1/disabled=0/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh
        mkdir -p files/etc
        cat << 'EOF' >> files/etc/sysctl.conf
        net.core.default_qdisc = cake
        net.ipv4.tcp_congestion_control = bbr
        net.core.netdev_max_backlog = 10000
        net.core.rmem_max = 16777216
        net.core.wmem_max = 16777216
        net.ipv4.tcp_rmem = 4096 87380 16777216
        net.ipv4.tcp_wmem = 4096 65536 16777216
        EOF
        make defconfig

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/mediatek/filogic
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to Artifacts
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_GL-MT3600BE_Firmware
        path: ${{ env.FIRMWARE }}/*sysupgrade.bin
