name: Build MPv (Windows X64)

on:
  workflow_dispatch:
    inputs:
      mpv_version:
        required: true
        default: v0.41.0

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Tools
        run: pip install meson ninja
      
      - name: Get Toolchain
        shell: bash
        run: |
          curl -L https://github.com/mstorsjo/llvm-mingw/releases/download/20240320/llvm-mingw-20240320-msvcrt-x86_64.zip -o llvm-mingw.zip
          unzip -q llvm-mingw.zip
          mv llvm-mingw-20240320-msvcrt-x86_64 llvm-mingw
      
      - name: Get mpv
        shell: bash
        run: |
          git clone https://github.com/mpv-player/mpv.git
          cd mpv
          git checkout ${{ inputs.mpv_version }}
          echo "#!/bin/sh" > version.sh
          echo "printf \"Lyra\"" >> version.sh
          chmod +x version.sh
      
      - name: Compile
        shell: bash
        run: |
          export PATH="$PWD/llvm-mingw/bin:$PATH"
          export CC=x86_64-w64-mingw32-clang
          export CXX=x86_64-w64-mingw32-clang++
          export AR=llvm-ar
          export STRIP=llvm-strip
          export CFLAGS="-O3 -mavx2 -funroll-loops -flto=full"
          export CXXFLAGS="$CFLAGS -fno-rtti -fno-exceptions"
          export LDFLAGS="-flto=full -static"
          
          cd mpv
          meson setup build --buildtype=release -Dcplayer=true -Dlibmpv=false -Dlua=disabled -Djavascript=disabled -Dvulkan=enabled -Dd3d11=enabled -Dwasapi=enabled
          ninja -C build
          $STRIP build/mpv.exe
          mv build/mpv.exe ../MPv.exe
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MPv
          path: MPv.exe
